 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainInterfaces;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import mycode.DBconnect;


/**
 *
 * @author Prabudha
 */
public class Reports extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
int x,y;
String a = null,b = null,c = null,d=null,e=null,f=null,g=null,h=null,i=null,userName;//for report object constructor
    /**
     * Creates new form Reports
     */
    public Reports(String ui) {
        initComponents();
        con = DBconnect.connect();
        String User = ui;
        lblUI.setText(User);
        this.userName=ui;
    }

    Reports() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblUI = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCusDetails = new javax.swing.JButton();
        btnListofItems = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnInventoryReceipt = new javax.swing.JButton();
        InventoryReturn = new javax.swing.JButton();
        SalesOrders = new javax.swing.JButton();
        SalesInvoicesDetails = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SalesInvoices1 = new javax.swing.JButton();
        SalesOrdersDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(3, 35, 55));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);

        jButton6.setBackground(new java.awt.Color(3, 35, 55));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainInterfaces/HED ICON.png"))); // NOI18N
        jButton6.setBorder(null);
        jPanel3.add(jButton6);
        jButton6.setBounds(10, 10, 30, 20);

        jButton7.setBackground(new java.awt.Color(3, 35, 55));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Programming-Minimize-Window-icon resize.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(480, 10, 30, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Reports");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(60, 10, 120, 20);

        lblUI.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblUI);
        lblUI.setBounds(180, 10, 140, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCusDetails.setBackground(new java.awt.Color(3, 35, 55));
        btnCusDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCusDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnCusDetails.setText("List of Customers");
        btnCusDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusDetailsActionPerformed(evt);
            }
        });

        btnListofItems.setBackground(new java.awt.Color(3, 35, 55));
        btnListofItems.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnListofItems.setForeground(new java.awt.Color(255, 255, 255));
        btnListofItems.setText("List of Items");
        btnListofItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListofItemsActionPerformed(evt);
            }
        });

        btnInventory.setBackground(new java.awt.Color(3, 35, 55));
        btnInventory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setText("Inventory");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });

        btnInventoryReceipt.setBackground(new java.awt.Color(3, 35, 55));
        btnInventoryReceipt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInventoryReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnInventoryReceipt.setText("Inventory Receipt");
        btnInventoryReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryReceiptActionPerformed(evt);
            }
        });

        InventoryReturn.setBackground(new java.awt.Color(3, 35, 55));
        InventoryReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InventoryReturn.setForeground(new java.awt.Color(255, 255, 255));
        InventoryReturn.setText("Inventory Return ");
        InventoryReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryReturnActionPerformed(evt);
            }
        });

        SalesOrders.setBackground(new java.awt.Color(3, 35, 55));
        SalesOrders.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SalesOrders.setForeground(new java.awt.Color(255, 255, 255));
        SalesOrders.setText("Sales Order Item Report");
        SalesOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesOrdersActionPerformed(evt);
            }
        });

        SalesInvoicesDetails.setBackground(new java.awt.Color(3, 35, 55));
        SalesInvoicesDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SalesInvoicesDetails.setForeground(new java.awt.Color(255, 255, 255));
        SalesInvoicesDetails.setText("Sales Invoice Item Report");
        SalesInvoicesDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesInvoicesDetailsActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SalesInvoices1.setBackground(new java.awt.Color(3, 35, 55));
        SalesInvoices1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SalesInvoices1.setForeground(new java.awt.Color(255, 255, 255));
        SalesInvoices1.setText("Sales Invoice Detail Report");
        SalesInvoices1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesInvoices1ActionPerformed(evt);
            }
        });

        SalesOrdersDetails.setBackground(new java.awt.Color(3, 35, 55));
        SalesOrdersDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SalesOrdersDetails.setForeground(new java.awt.Color(255, 255, 255));
        SalesOrdersDetails.setText("Sales Order / Receipt Detail Report");
        SalesOrdersDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesOrdersDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalesInvoices1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalesOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalesInvoicesDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalesOrdersDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InventoryReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventoryReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListofItems, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCusDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCusDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListofItems, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInventoryReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InventoryReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalesOrdersDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalesOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalesInvoices1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalesInvoicesDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCusDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusDetailsActionPerformed
                  
               
        reportFilter repFil = new reportFilter(a,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);       
                             
        
    }//GEN-LAST:event_btnCusDetailsActionPerformed

    private void btnListofItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListofItemsActionPerformed

           
        reportFilter repFil = new reportFilter(a,b,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);

    }//GEN-LAST:event_btnListofItemsActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed

               
        reportFilter repFil = new reportFilter(a,b,c,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);
       
 
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnInventoryReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryReceiptActionPerformed
        reportFilter repFil = new reportFilter(a,b,c,d,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);
    }//GEN-LAST:event_btnInventoryReceiptActionPerformed

    private void InventoryReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryReturnActionPerformed
        reportFilter repFil = new reportFilter(a,b,c,d,e,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);
    }//GEN-LAST:event_InventoryReturnActionPerformed

    private void SalesOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesOrdersActionPerformed
        reportFilter repFil = new reportFilter(a,b,c,d,e,f,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);
    }//GEN-LAST:event_SalesOrdersActionPerformed

    private void SalesInvoicesDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesInvoicesDetailsActionPerformed
        reportFilter repFil = new reportFilter(a,b,c,d,e,f,g,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);
    }//GEN-LAST:event_SalesInvoicesDetailsActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setExtendedState(HomePage.ICONIFIED);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged

        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed

        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SalesInvoices1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesInvoices1ActionPerformed
         reportFilter repFil = new reportFilter(a,b,c,d,e,f,g,h,i,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);
    }//GEN-LAST:event_SalesInvoices1ActionPerformed

    private void SalesOrdersDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesOrdersDetailsActionPerformed

        reportFilter repFil = new reportFilter(a,b,c,d,e,f,g,h,userName);
        repFil.setVisible(true);
        //this.setExtendedState(reportFilter.ICONIFIED);

    }//GEN-LAST:event_SalesOrdersDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InventoryReturn;
    private javax.swing.JButton SalesInvoices1;
    private javax.swing.JButton SalesInvoicesDetails;
    private javax.swing.JButton SalesOrders;
    private javax.swing.JButton SalesOrdersDetails;
    private javax.swing.JButton btnCusDetails;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnInventoryReceipt;
    private javax.swing.JButton btnListofItems;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblUI;
    // End of variables declaration//GEN-END:variables





}
